# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: GitHub Action for Yarn
  # You may pin to the exact commit or the version.
  # uses: Borales/actions-yarn@4965e1a0f0ae9c422a9a5748ebd1fb5e097d22b9
        uses: Borales/actions-yarn@v2.3.0
        with:
          # Yarn command "install" the yarn
          cmd: install
      
      - name: Create Build for Production (minimzed version of packages, json, node_modules)
        run:  yarn build
          
      - name: Install Surge
        run: npm install --global surge  
        
      - name: Deploy Basic App to Surge
        run: surge ./build http://react-app-0.surge.sh/ --token ${{ secrets.surgeToken }}
